api/urls.py
from django.urls import path
from .views import BookDetailAPIView, BookListAPIView


app_name = 'api'


urlpatterns  = [
    path('reviews/<int:id>/', BookDetailAPIView.as_view(), name='detail'),
    path('reviews/', BookListAPIView.as_view(), name='list'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import landing_page, home_page
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_page, name='main'),
    path('home/', home_page, name='home'),

    # API URLS
    path('api/', include('api.urls')),
    
    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import LoginView, RegisterView, ProfileView, LogOutView, ProfileUpdateView



app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogOutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', ProfileUpdateView.as_view(), name='profile-edit'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    image = models.ImageField(upload_to='media/', default='default_profile_pic.jpg')
    

users/forms.py
from django import forms
from users.models import CustomUser
from django.shortcuts import redirect


class UserCreateForm(forms.Form):
    username = forms.CharField(max_length=150)
    first_name = forms.CharField(max_length=150)
    last_name = forms.CharField(max_length=150)
    email = forms.EmailField()
    password = forms.CharField(max_length=120)

    def save(self):
        username = self.cleaned_data['username']
        first_name = self.cleaned_data['first_name']
        last_name = self.cleaned_data['last_name']
        email = self.cleaned_data['email']
        password = self.cleaned_data['password']

        user = CustomUser.objects.create(
            username=username, 
            first_name=first_name, 
            last_name=last_name, 
            email=email
        )
        user.set_password(password)
        user.save()

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'first_name', 'last_name', 'email','image')

users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from users.forms import UserCreateForm, UserUpdateForm
from users.models import CustomUser
from django.views import View
from django.shortcuts import render, redirect
from django.contrib import messages


class RegisterView(View):
    def get(self, request):
        create_form = UserCreateForm()
        context = {
            'form':create_form
        }
        return render(request, 'users/register.html', context=context)
    
    def post(self, request):
        create_forms = UserCreateForm(data=request.POST)

        if create_forms.is_valid():
            create_forms.save()
            return redirect('users:login')
        else:
            context = {
                'form':create_forms
            }
            return render(request, 'users/register.html', context)
        

class LoginView(View):
    def get(self, request):

        login_form = AuthenticationForm()
        context = {
            'login_form':login_form
        }
        return render(request, 'users/login.html', context)
    

    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)

        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            messages.success(request, 'You successfully logged in.')
            context = {
                'login_form':login_form
            }
            return redirect('books:list')
        else:
            context = {
                'login_form':login_form
            }
            return render(request, 'users/login.html', context=context)


class ProfileView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'users/profiles.html', {'user':request.user})
    
    

class LogOutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request) 
        messages.info(request, 'You successfully logged out.')
        return redirect('main')


class ProfileUpdateView(LoginRequiredMixin, View):
    def get(self, request):
        user_update_form = UserUpdateForm(instance=request.user)
        context = {
            'update_form':user_update_form
        }
        return render(request, 'users/profile-edit.html', context=context)
    
    def post(self, request):
        user_update_form = UserUpdateForm(
            instance=request.user,
            data=request.POST,
            files=request.FILES,
        )

        if user_update_form.is_valid():
            user_update_form.save()
            messages.success(request,"You have successfully updated profile.")
            return redirect('users:profile')
        
        context = {
            'update_form':user_update_form
        }
        return render(request, 'users/profile-edit.html', context=context)

users/templates/users/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Login Page{% endblock %}

{% block content %}

<h3>Login</h1>

<div class="row">
    <div class="col-4">
        <form method="post">
            {%csrf_token%}
            
            {{login_form | crispy}}
            
            <button class="btn btn-primary">Log in</button> No accaunt? Then <a href="{% url 'users:register' %}"> get register</a>
        </form>
    </div>
</div>


{% endblock %}

users/templates/users/profile-edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Profile Edit{% endblock %}

{% block content %}

<h3>Profile Edit</h3>
<div class="row">
    <div class="col-4">
        <form method="post">
            {%csrf_token%}
            {{ update_form | crispy }}
        
            <button class="btn btn-primary mt-2">save changes</button>
        </form>
    </div>
</div>

{% endblock %}

users/templates/users/profiles.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Profile{% endblock %}

{% block content %}


<h1>Profile</h1>
<div class="container mt-4 mb-4 p-3 d-flex justify-content-center"> 
    <div class="card p-4"> 
        <div class=" image d-flex flex-column justify-content-center align-items-center"> 
            <button class="btn btn-secondary"> 
                <img src="{{ user.image.url }}" alt="" class="profile-pic">
            </button>
            <span class="name mt-3">{{user.first_name}} {{user.last_name}}</span> 
            <span class="idd">@{{user.username}}</span> 
            <span class="idd">{{user.email}}</span> 
            <div class=" d-flex mt-2"> 
                <a class="btn1 btn-dark" href="{% url 'users:profile-edit' %}">Edit Profile</a> 
            </div> 
            <div class=" px-2 rounded mt-4 date "> 
                <span class="join">{{user.data_joined}}</span> 
            </div> 
        </div> 
    </div>
</div>
<!-- <div>
    
</div>
<p>Username:{{user.username}}</p>
<p>First Name:{{user.first_name}}</p>
<p>Last Name:{{user.last_name}}</p>
<p>Email:{{user.email}}</p> -->

{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Register Page{% endblock %}

{% block content %}

<h3>Register</h3>

<div class="row">
    <div class="col-4">
        <form action="{% url 'users:register' %}" method="post">
            {% csrf_token %}
            {{form|crispy}}
        
            <button class="btn btn-primary" type="submit">Submit</button>
        </form>
    </div>
</div>

{% endblock %}