api/urls.py
from django.urls import path
from .views import BookDetailAPIView, BookListAPIView


app_name = 'api'


urlpatterns  = [
    path('reviews/<int:id>/', BookDetailAPIView.as_view(), name='detail'),
    path('reviews/', BookListAPIView.as_view(), name='list'),

]

books/urls.py
from django.urls import path

from .views import BookListView, BookDetailView, AddReviewView, EditReviewView, ConfirmDeleteView, DeleteReviewView

app_name = 'books'
urlpatterns = [
    path("", BookListView.as_view(), name='list'),
    path('<int:id>/', BookDetailView.as_view(), name='detail'),
    path('<int:id>/reviews/', AddReviewView.as_view(), name='reviews'),
    path('<int:book_id>/review/<int:review_id>/edit/', EditReviewView.as_view(), name='edit_review_view'),
    path('<int:book_id>/review/<int:review_id>/delete/confirm/', ConfirmDeleteView.as_view(), name='delete_confirm_review_view'),
    path('<int:book_id>/review/<int:review_id>/delete/', DeleteReviewView.as_view(), name='delete_review_view'),


    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import landing_page, home_page
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_page, name='main'),
    path('home/', home_page, name='home'),

    # API URLS
    path('api/', include('api.urls')),
    
    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.views import LoginView, RegisterView, ProfileView, LogOutView, ProfileUpdateView



app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogOutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/', ProfileUpdateView.as_view(), name='profile-edit'),
]

templates/base.html
{% load static %}
{% url 'home' as home_page_url %}
{% url 'books:list' as books_page_url %}
{% url 'users:profile' as profile_page_url %}
{% url 'users:profile-edit' as profile_edit_page_url %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>{% block title %}Main Page{% endblock %}</title>
</head>
<body class="container">
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'main' %}">Goodreads</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link {% if request.path == home_page_url %} active {% endif %}" aria-current="page" href="{{ home_page_url }}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if request.path == books_page_url %} active {% endif %}" aria-current="page" href="{{books_page_url}}">Books</a>
        </li>
      </ul>

      {% if request.user.is_authenticated %}
        <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle {% if request.path == profile_page_url or request.path == profile_edit_page_url %} active {% endif %}" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  {{request.user.username}}
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item " href="{{profile_page_url}}">Profile</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item text-danger" href="{% url 'users:logout' %}">Log Out</a></li>
                </ul>
            </li>
        </ul>
    {% else %}
        <a href="{% url 'users:login' %}" class="btn btn-outline-light">LogIn</a>
    {% endif %}
    </div>
  </div>
</nav>
<div class="container">
  {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                {{message}}
            
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  {% endfor %}
{% endif %}


{% block content %}{% endblock %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home Page{% endblock %}

{% block content %}

<div class="container posts-content">
{% for review in page_obj %}
    <div class="row">
        <div class="col-lg-6">
            <div class="card mb-4">
              <div class="card-body">
                <div class="media mb-3">
                  <img src="{{review.user.image.url}}" class="d-block ui-w-40 rounded-circle" alt="">
                  <div class="media-body ml-3">
                    {{review.user.username}}
                    <div class="text-muted small">{{review.created_at | date:'D m, Y'}}</div>
                  </div>
                </div>
            
                <p>
                  {{review.comment|truncatewords:50}}
                </p>
                <img src="{{review.book.image.url}}" alt="" class="ui-rect ui-bg-cover">
              </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <nav aria-label="Page navigation example">
        <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
        {% endif %}
          <li class="page-item"><a class="page-link" href="#">{{page_obj.number}}</a></li>
        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
        {% endif %}
        </ul>
    </nav>
</div>

{% endblock %}

templates/landing_page.html
{% extends 'base.html' %}

{% block title %}Landing Page{% endblock %}

{% block content %}
<h1>Landing Page</h1>
{% endblock %}