api/urls.py
from django.urls import path
from .views import BookDetailAPIView, BookListAPIView


app_name = 'api'


urlpatterns  = [
    path('reviews/<int:id>/', BookDetailAPIView.as_view(), name='detail'),
    path('reviews/', BookListAPIView.as_view(), name='list'),

]

books/urls.py
from django.urls import path

from .views import BookListView, BookDetailView, AddReviewView, EditReviewView, ConfirmDeleteView, DeleteReviewView

app_name = 'books'
urlpatterns = [
    path("", BookListView.as_view(), name='list'),
    path('<int:id>/', BookDetailView.as_view(), name='detail'),
    path('<int:id>/reviews/', AddReviewView.as_view(), name='reviews'),
    path('<int:book_id>/review/<int:review_id>/edit/', EditReviewView.as_view(), name='edit_review_view'),
    path('<int:book_id>/review/<int:review_id>/delete/confirm/', ConfirmDeleteView.as_view(), name='delete_confirm_review_view'),
    path('<int:book_id>/review/<int:review_id>/delete/', DeleteReviewView.as_view(), name='delete_review_view'),


    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import landing_page, home_page
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', landing_page, name='main'),
    path('home/', home_page, name='home'),

    # API URLS
    path('api/', include('api.urls')),
    
    path('users/', include('users.urls')),
    path('books/', include('books.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from users.models import CustomUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone

class Book(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    isbn = models.CharField(max_length=50)
    image = models.ImageField(null=True, blank=True, default='cover.png', upload_to='media' )

    def __str__(self):
        return self.title


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    bio = models.TextField()

    def __str__(self):
        return f'{self.full_name}'
        
    def full_name(self):
        return f'{self.first_name} {self.last_name}'

class BookAuthor(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.book.title} by {self.author.first_name}'

    


class BookReview(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='reviews')
    comment = models.TextField()
    stars_given = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.stars_given} stars by {self.user}'

books/forms.py
from django import forms
from books.models import BookReview

class BookReviewForm(forms.ModelForm):
    stars_given = forms.IntegerField(min_value=1, max_value=5)
    class Meta:
        model = BookReview
        fields = ('stars_given', 'comment')

        

books/views.py
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import View
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator
from books.forms import BookReviewForm
from books.models import Book, BookReview
from django.contrib.auth.mixins import LoginRequiredMixin   
from django.contrib import messages

class BookListView(View):
    def get(self, request):
        books = Book.objects.all().order_by('id')

        search_query = request.GET.get("q", '')

        
        if search_query:
            books = books.filter(title__icontains=search_query)
            

        page_size = request.GET.get('page_size', 4)
        paginator = Paginator(books, page_size)

        page_number = request.GET.get('page', 1)
        page_obj = paginator.get_page(page_number)


        return render(request, 'books/book_list.html',
                    {'page_obj':page_obj,'search_query':search_query,})
    
class BookDetailView(View):
    def get(self, request, id):
        book = Book.objects.get(id=id)
        review_form = BookReviewForm()
        context = {
            'book':book,
            'review_form':review_form
        }
        return render(request, 'books/book_detail.html', context)
    

class AddReviewView(LoginRequiredMixin, View):
    def post(self, request, id):
        book = Book.objects.get(id=id)
        review_form = BookReviewForm(data=request.POST)
        if review_form.is_valid():
            BookReview.objects.create(
                book=book,
                user=request.user,
                stars_given=review_form.cleaned_data['stars_given'],
                comment=review_form.cleaned_data['comment'],
            )
            return redirect(reverse('books:detail', kwargs={'id':book.id}))
        
        context = {
            'book':book,
            'review_form':review_form
        }
        return render(request, 'books/book_detail.html', context)


class EditReviewView(View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.reviews.get(id=review_id)
        review_form = BookReviewForm(instance=review)
        context = {
            'book':book,
            'review':review,
            'review_form':review_form
        }
        return render(request, 'books/edit-review.html', context)
    
    def post(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.reviews.get(id=review_id)
        review_form = BookReviewForm(instance=review, data=request.POST)

        if review_form.is_valid:
            review_form.save()
            
            return redirect(reverse('books:detail', kwargs={'id': book.id}))
        context = {
            'book':book,
            'review':review,
            'review_form':review_form
        }
        return render(request, 'books/edit-review.html', context)
        

class ConfirmDeleteView(View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.reviews.get(id=review_id)
        context = {
            'book': book,
            'review': review
        }
        return render(request, 'books/confirm-delete.html', context)

class DeleteReviewView(View):
    def get(self, request, book_id, review_id):
        book = Book.objects.get(id=book_id)
        review = book.reviews.get(id=review_id)

        review.delete()
        messages.success(request, 'Review successfully deleted')

        return redirect(reverse('books:detail', kwargs={'id':book.id}))

books/templates/books/book_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Book Detail Page{% endblock %}

{% block content %}

<div class="row mb-3">
    <div class="col-2 ">
        <img src="{{book.image.url}}" class="books" alt="">
    </div>
    <div class="col-6 ms-5">
        <h3>{{book.title}}</h3>
        <b>Author: </b>
        {% for book_author in book.bookauthor_set.all %}
        
            {% if forloop.last %}
                <i>{{book_author.author.full_name}}</i>
            {% else %}
                <i>{{book_author.author.full_name}},</i>
            {% endif %}
        {% endfor %}
        <p>
            {{book.description}}
        </p>
    </div>
</div>  
{% if user.is_authenticated %}
<div class="row">
    <div class="col-6">
        <form method="post" action="{% url 'books:reviews' book.id %}">
            {% csrf_token %}
            {{review_form|crispy}}
            <button class="btn btn-success">Add Review</button>
        </form>
    </div>
</div>
{% endif %}

{% if book.reviews.exists %}

    <h3>Reviews</h3> <hr>
    {% for review in book.reviews.all %}
        <div class="row">
            <div class="col-7">
                <img src="{{review.user.image.url}}" class="m-1" style="width: 30px; height: 30px; border-radius: 50%;"><b>{{review.user}}</b> <i class='fw-light'>{{review.created_at}}</i>
                {% if review.user == request.user %}
                    <a href="{% url 'books:edit_review_view' book.id review.id %}"><i class="bi bi-pen"></i></a>
                    <a href="{% url 'books:delete_confirm_review_view' book.id review.id %}"><i class="bi bi-trash"></i></a>
                {% endif %}
                <p class='fst-italic'>{{review.comment}}</p>
            </div>
        </div> 
    {% endfor %}
{% endif %}
{% endblock %}

books/templates/books/book_list.html
{% extends 'base.html' %}

{% block title %}Books{% endblock %}

{% block content %}
<h1>Books</h1>
<div class="row mb-5">
    <div class="col-6 ">
        <form method="GET" class="d-flex">
            <input type="text"  placeholder="search" class="form-control me-2" name="q" id="q">

            <button class="btn btn-success">Search</button>
        </form>
    </div>
</div>
{% if page_obj %}
        {% for book in page_obj.object_list %}
        <div class="row mb-3">
            <div class="col-2 ">
                <img src="{{ book.image.url }}" class="books">
            </div>
            <div class="col-6 ms-5">
                <a href="{% url 'books:detail' book.id %}">{{book.title}}</a>
                <p>
                    {{book.description|truncatewords:70}} 
                </p>
                <p>
                    <a href="{% url 'books:detail' book.id %}">show more..</a>
                </p>
            </div>
        </div>    
        {% endfor %}
        <nav aria-label="Page navigation example">
            <ul class="pagination">
            {% if page_obj.has_previous %}
              <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
            {% endif %}
              <li class="page-item"><a class="page-link" href="#">{{page_obj.number}}</a></li>
            {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
            {% endif %}
            </ul>
          </nav>
{% else %}
    No found book.
{% endif %}
{% endblock %}

books/templates/books/confirm-delete.html
{% extends 'base.html' %}

{% block title %} Confirm Delete Page  {% endblock %}

{% block content %}

<h3>Confirm Delete Page</h3>

<p>
    <b>Book:</b> {{book.title}}
</p>

<p>
    <b>Comment:</b> {{review.comment}}
</p>

<a href="{% url 'books:delete_review_view' book.id review.id %}" class="btn btn-outline-danger">Delete</a>

<a href="{% url 'books:detail' book.id %}" class="btn btn-outline-primary">Back</a>

{% endblock %}

books/templates/books/edit-review.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Update Review {% endblock %}

{% block content %}

<h3>Update Review Page</h3>

<div class="row">
    <div class="col-6">
        <form method="post">
            {% csrf_token %}
            {{review_form|crispy}}
            <button class="btn btn-success">Save Review</button>
        </form>
    </div>
</div>

{% endblock %}